# Generated by Django 2.1.2 on 2018-10-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название места')),
                ('coordinate_x', models.TextField(verbose_name='Долгота')),
                ('coordinate_y', models.TextField(verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
        migrations.CreateModel(
            name='Urn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete='CASCADE', related_name='location_urns', to='main.Location', verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Мусорка',
                'verbose_name_plural': 'Мусорки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(verbose_name='Логин')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('fio', models.TextField(verbose_name='ФИО')),
                ('nickname', models.TextField(verbose_name='Никнейм')),
                ('score', models.TextField(verbose_name='Баланс баллов')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
