# Generated by Django 2.1.2 on 2018-10-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181013_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urn',
            name='types',
        ),
        migrations.AddField(
            model_name='urn',
            name='trash_type',
            field=models.TextField(choices=[('GLASS', 'GLASS'), ('PLASTIC', 'PLASTIC'), ('PAPER', 'PAPER'), ('METAL', 'METAL'), ('BATTERIES', 'BATTERIES'), ('OTHER', 'OTHER')], default=1, verbose_name='Тип мусора'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TypesUrn',
        ),
    ]
